// <auto-generated />
using System;
using Chiniseapp.Domain.Enums;
using Chiniseapp.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Chiniseapp.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ChiniseDbContext))]
    partial class ChiniseDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "audit_action", new[] { "created", "status_changed", "content_edited", "role_changed", "deactivated", "archived", "repair_mode_toggled", "other" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "comment_status", new[] { "open", "archived" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "editor_role", new[] { "super_admin", "chief_editor", "zh_editor", "ka_editor", "assistant_editor" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "entry_status", new[] { "new_entry", "zh_review", "ka_review", "ready", "published", "archived" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "media_file_type", new[] { "image", "video" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "placement", new[] { "inline", "attached", "standalone" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "score_type", new[] { "main", "additional", "ka_editor" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "segment_type", new[] { "homonym", "gram_grp", "pos", "sense", "definition", "example", "zh_segment", "ka_segment", "xr", "style", "domain", "abbr", "lang" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "vocabulary_category", new[] { "pos", "style", "domain", "abbr", "lang" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Chiniseapp.Domain.Entities.AuditLogEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<AuditAction>("Action")
                        .HasColumnType("audit_action")
                        .HasColumnName("action");

                    b.Property<int>("EntityId")
                        .HasColumnType("integer")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("entity_type");

                    b.Property<string>("NewValue")
                        .HasColumnType("jsonb")
                        .HasColumnName("new_value");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("OldValue")
                        .HasColumnType("jsonb")
                        .HasColumnName("old_value");

                    b.Property<DateTime>("PerformedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("performed_at_utc");

                    b.Property<int>("PerformedByEditorId")
                        .HasColumnType("integer")
                        .HasColumnName("performed_by_editor_id");

                    b.HasKey("Id")
                        .HasName("pk_audit_log_entries");

                    b.HasIndex("PerformedByEditorId")
                        .HasDatabaseName("ix_audit_log_entries_performed_by_editor_id");

                    b.HasIndex("EntityType", "EntityId")
                        .HasDatabaseName("ix_audit_log_entries_entity_type_entity_id");

                    b.ToTable("audit_log_entries", (string)null);
                });

            modelBuilder.Entity("Chiniseapp.Domain.Entities.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorEditorId")
                        .HasColumnType("integer")
                        .HasColumnName("author_editor_id");

                    b.Property<string>("CommentText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("comment_text");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<int>("EntryId")
                        .HasColumnType("integer")
                        .HasColumnName("entry_id");

                    b.Property<string>("OriginalRawComment")
                        .HasColumnType("text")
                        .HasColumnName("original_raw_comment");

                    b.Property<string>("ParsedCommentParts")
                        .HasColumnType("jsonb")
                        .HasColumnName("parsed_comment_parts");

                    b.Property<CommentStatus>("Status")
                        .HasColumnType("comment_status")
                        .HasColumnName("status");

                    b.Property<int?>("TargetSegmentId")
                        .HasColumnType("integer")
                        .HasColumnName("target_segment_id");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_comments");

                    b.HasIndex("AuthorEditorId")
                        .HasDatabaseName("ix_comments_author_editor_id");

                    b.HasIndex("EntryId")
                        .HasDatabaseName("ix_comments_entry_id");

                    b.HasIndex("TargetSegmentId")
                        .HasDatabaseName("ix_comments_target_segment_id");

                    b.ToTable("comments", (string)null);
                });

            modelBuilder.Entity("Chiniseapp.Domain.Entities.ControlledVocabulary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<VocabularyCategory>("Category")
                        .HasColumnType("vocabulary_category")
                        .HasColumnName("category");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<string>("DisplayKa")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("display_ka");

                    b.Property<string>("DisplayZh")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("display_zh");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("Id")
                        .HasName("pk_controlled_vocabularies");

                    b.HasIndex("Category", "Code")
                        .IsUnique()
                        .HasDatabaseName("ix_controlled_vocabularies_category_code");

                    b.ToTable("controlled_vocabularies", (string)null);
                });

            modelBuilder.Entity("Chiniseapp.Domain.Entities.DirectMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<DateTime?>("ReadAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("read_at_utc");

                    b.Property<int>("RecipientEditorId")
                        .HasColumnType("integer")
                        .HasColumnName("recipient_editor_id");

                    b.Property<int>("SenderEditorId")
                        .HasColumnType("integer")
                        .HasColumnName("sender_editor_id");

                    b.Property<DateTime>("SentAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_direct_messages");

                    b.HasIndex("SenderEditorId")
                        .HasDatabaseName("ix_direct_messages_sender_editor_id");

                    b.HasIndex("RecipientEditorId", "ReadAtUtc")
                        .HasDatabaseName("ix_direct_messages_recipient_editor_id_read_at_utc");

                    b.ToTable("direct_messages", (string)null);
                });

            modelBuilder.Entity("Chiniseapp.Domain.Entities.Editor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("LastLoginAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at_utc");

                    b.Property<string>("LegacyRoleRaw")
                        .HasColumnType("text")
                        .HasColumnName("legacy_role_raw");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<EditorRole>("Role")
                        .HasColumnType("editor_role")
                        .HasColumnName("role");

                    b.HasKey("Id")
                        .HasName("pk_editors");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_editors_email");

                    b.ToTable("editors", (string)null);
                });

            modelBuilder.Entity("Chiniseapp.Domain.Entities.Entry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<int>("CreatedByEditorId")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_editor_id");

                    b.Property<bool>("IsFlaggedForRepair")
                        .HasColumnType("boolean")
                        .HasColumnName("is_flagged_for_repair");

                    b.Property<int>("LastEditorEditorId")
                        .HasColumnType("integer")
                        .HasColumnName("last_editor_editor_id");

                    b.Property<string>("LegacyRawCommentBlob")
                        .HasColumnType("text")
                        .HasColumnName("legacy_raw_comment_blob");

                    b.Property<string>("Lemma")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("lemma");

                    b.Property<int?>("MainAuthorEditorId")
                        .HasColumnType("integer")
                        .HasColumnName("main_author_editor_id");

                    b.Property<string>("Pinyin")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("pinyin");

                    b.Property<string>("RepairNotes")
                        .HasColumnType("text")
                        .HasColumnName("repair_notes");

                    b.Property<string>("SearchNormalizedTitle")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("search_normalized_title");

                    b.Property<EntryStatus>("Status")
                        .HasColumnType("entry_status")
                        .HasColumnName("status");

                    b.Property<int>("StatusPriority")
                        .HasColumnType("integer")
                        .HasColumnName("status_priority");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_entries");

                    b.HasIndex("CreatedByEditorId")
                        .HasDatabaseName("ix_entries_created_by_editor_id");

                    b.HasIndex("LastEditorEditorId")
                        .HasDatabaseName("ix_entries_last_editor_editor_id");

                    b.HasIndex("MainAuthorEditorId")
                        .HasDatabaseName("ix_entries_main_author_editor_id");

                    b.HasIndex("SearchNormalizedTitle")
                        .HasDatabaseName("ix_entries_search_normalized_title");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("SearchNormalizedTitle"), "btree");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("SearchNormalizedTitle"), new[] { "text_pattern_ops" });

                    b.HasIndex("StatusPriority", "UpdatedAtUtc")
                        .HasDatabaseName("ix_entries_status_priority_updated_at_utc")
                        .HasFilter("status <> 'new_entry'");

                    b.ToTable("entries", (string)null);
                });

            modelBuilder.Entity("Chiniseapp.Domain.Entities.MediaAsset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<MediaFileType>("FileType")
                        .HasColumnType("media_file_type")
                        .HasColumnName("file_type");

                    b.Property<int?>("InsertedIntoSegmentId")
                        .HasColumnType("integer")
                        .HasColumnName("inserted_into_segment_id");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("mime_type");

                    b.Property<string>("OriginalFilename")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("original_filename");

                    b.Property<string>("Placement")
                        .HasColumnType("text")
                        .HasColumnName("placement");

                    b.Property<string>("SafeStorageName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("safe_storage_name");

                    b.Property<string>("StorageUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("storage_url");

                    b.Property<string>("ThumbnailUrl")
                        .HasColumnType("text")
                        .HasColumnName("thumbnail_url");

                    b.Property<DateTime>("UploadedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploaded_at_utc");

                    b.Property<int>("UploadedByEditorId")
                        .HasColumnType("integer")
                        .HasColumnName("uploaded_by_editor_id");

                    b.HasKey("Id")
                        .HasName("pk_media_assets");

                    b.HasIndex("InsertedIntoSegmentId")
                        .HasDatabaseName("ix_media_assets_inserted_into_segment_id");

                    b.HasIndex("UploadedByEditorId")
                        .HasDatabaseName("ix_media_assets_uploaded_by_editor_id");

                    b.ToTable("media_assets", (string)null);
                });

            modelBuilder.Entity("Chiniseapp.Domain.Entities.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<int>("EntryId")
                        .HasColumnType("integer")
                        .HasColumnName("entry_id");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean")
                        .HasColumnName("is_read");

                    b.Property<int>("RecipientEditorId")
                        .HasColumnType("integer")
                        .HasColumnName("recipient_editor_id");

                    b.Property<int>("TriggeredByEditorId")
                        .HasColumnType("integer")
                        .HasColumnName("triggered_by_editor_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_notifications");

                    b.HasIndex("EntryId")
                        .HasDatabaseName("ix_notifications_entry_id");

                    b.HasIndex("TriggeredByEditorId")
                        .HasDatabaseName("ix_notifications_triggered_by_editor_id");

                    b.HasIndex("RecipientEditorId", "IsRead")
                        .HasDatabaseName("ix_notifications_recipient_editor_id_is_read");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("Chiniseapp.Domain.Entities.ReferenceMaterial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<int>("EntryId")
                        .HasColumnType("integer")
                        .HasColumnName("entry_id");

                    b.Property<string>("G1")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("g1");

                    b.Property<string>("G2")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("g2");

                    b.Property<string>("G3")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("g3");

                    b.Property<string>("G4")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("g4");

                    b.Property<string>("G5")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("g5");

                    b.Property<string>("OriginalRawReferenceMaterial")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("original_raw_reference_material");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_reference_materials");

                    b.HasIndex("EntryId")
                        .IsUnique()
                        .HasDatabaseName("ix_reference_materials_entry_id");

                    b.ToTable("reference_materials", (string)null);
                });

            modelBuilder.Entity("Chiniseapp.Domain.Entities.ScoreEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AwardedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("awarded_at_utc");

                    b.Property<int>("EditorId")
                        .HasColumnType("integer")
                        .HasColumnName("editor_id");

                    b.Property<int>("EntryId")
                        .HasColumnType("integer")
                        .HasColumnName("entry_id");

                    b.Property<ScoreType>("ScoreType")
                        .HasColumnType("score_type")
                        .HasColumnName("score_type");

                    b.HasKey("Id")
                        .HasName("pk_score_entries");

                    b.HasIndex("EditorId")
                        .HasDatabaseName("ix_score_entries_editor_id");

                    b.HasIndex("EntryId", "EditorId", "ScoreType")
                        .IsUnique()
                        .HasDatabaseName("ix_score_entries_entry_id_editor_id_score_type");

                    b.ToTable("score_entries", (string)null);
                });

            modelBuilder.Entity("Chiniseapp.Domain.Entities.Segment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Attributes")
                        .HasColumnType("jsonb")
                        .HasColumnName("attributes");

                    b.Property<string>("Content")
                        .HasColumnType("jsonb")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<int>("EntryId")
                        .HasColumnType("integer")
                        .HasColumnName("entry_id");

                    b.Property<int?>("Number")
                        .HasColumnType("integer")
                        .HasColumnName("number");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer")
                        .HasColumnName("order_index");

                    b.Property<int?>("ParentSegmentId")
                        .HasColumnType("integer")
                        .HasColumnName("parent_segment_id");

                    b.Property<Placement?>("Placement")
                        .HasColumnType("placement")
                        .HasColumnName("placement");

                    b.Property<SegmentType>("SegmentType")
                        .HasColumnType("segment_type")
                        .HasColumnName("segment_type");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_segments");

                    b.HasIndex("EntryId")
                        .HasDatabaseName("ix_segments_entry_id");

                    b.HasIndex("ParentSegmentId")
                        .HasDatabaseName("ix_segments_parent_segment_id");

                    b.HasIndex("EntryId", "ParentSegmentId", "OrderIndex")
                        .HasDatabaseName("ix_segments_entry_id_parent_segment_id_order_index");

                    b.ToTable("segments", (string)null);
                });

            modelBuilder.Entity("Chiniseapp.Domain.Entities.AuditLogEntry", b =>
                {
                    b.HasOne("Chiniseapp.Domain.Entities.Editor", null)
                        .WithMany()
                        .HasForeignKey("PerformedByEditorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_audit_log_entries_editors_performed_by_editor_id");
                });

            modelBuilder.Entity("Chiniseapp.Domain.Entities.Comment", b =>
                {
                    b.HasOne("Chiniseapp.Domain.Entities.Editor", null)
                        .WithMany()
                        .HasForeignKey("AuthorEditorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_comments_editors_author_editor_id");

                    b.HasOne("Chiniseapp.Domain.Entities.Entry", null)
                        .WithMany()
                        .HasForeignKey("EntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_comments_entries_entry_id");

                    b.HasOne("Chiniseapp.Domain.Entities.Segment", null)
                        .WithMany()
                        .HasForeignKey("TargetSegmentId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_comments_segments_target_segment_id");
                });

            modelBuilder.Entity("Chiniseapp.Domain.Entities.DirectMessage", b =>
                {
                    b.HasOne("Chiniseapp.Domain.Entities.Editor", null)
                        .WithMany()
                        .HasForeignKey("RecipientEditorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_direct_messages_editors_recipient_editor_id");

                    b.HasOne("Chiniseapp.Domain.Entities.Editor", null)
                        .WithMany()
                        .HasForeignKey("SenderEditorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_direct_messages_editors_sender_editor_id");
                });

            modelBuilder.Entity("Chiniseapp.Domain.Entities.Entry", b =>
                {
                    b.HasOne("Chiniseapp.Domain.Entities.Editor", null)
                        .WithMany()
                        .HasForeignKey("CreatedByEditorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_entries_editors_created_by_editor_id");

                    b.HasOne("Chiniseapp.Domain.Entities.Editor", null)
                        .WithMany()
                        .HasForeignKey("LastEditorEditorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_entries_editors_last_editor_editor_id");

                    b.HasOne("Chiniseapp.Domain.Entities.Editor", null)
                        .WithMany()
                        .HasForeignKey("MainAuthorEditorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_entries_editors_main_author_editor_id");
                });

            modelBuilder.Entity("Chiniseapp.Domain.Entities.MediaAsset", b =>
                {
                    b.HasOne("Chiniseapp.Domain.Entities.Segment", null)
                        .WithMany()
                        .HasForeignKey("InsertedIntoSegmentId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_media_assets_segments_inserted_into_segment_id");

                    b.HasOne("Chiniseapp.Domain.Entities.Editor", null)
                        .WithMany()
                        .HasForeignKey("UploadedByEditorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_media_assets_editors_uploaded_by_editor_id");
                });

            modelBuilder.Entity("Chiniseapp.Domain.Entities.Notification", b =>
                {
                    b.HasOne("Chiniseapp.Domain.Entities.Entry", null)
                        .WithMany()
                        .HasForeignKey("EntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_notifications_entries_entry_id");

                    b.HasOne("Chiniseapp.Domain.Entities.Editor", null)
                        .WithMany()
                        .HasForeignKey("RecipientEditorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_notifications_editors_recipient_editor_id");

                    b.HasOne("Chiniseapp.Domain.Entities.Editor", null)
                        .WithMany()
                        .HasForeignKey("TriggeredByEditorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_notifications_editors_triggered_by_editor_id");
                });

            modelBuilder.Entity("Chiniseapp.Domain.Entities.ReferenceMaterial", b =>
                {
                    b.HasOne("Chiniseapp.Domain.Entities.Entry", null)
                        .WithOne()
                        .HasForeignKey("Chiniseapp.Domain.Entities.ReferenceMaterial", "EntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_reference_materials_entries_entry_id");
                });

            modelBuilder.Entity("Chiniseapp.Domain.Entities.ScoreEntry", b =>
                {
                    b.HasOne("Chiniseapp.Domain.Entities.Editor", null)
                        .WithMany()
                        .HasForeignKey("EditorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_score_entries_editors_editor_id");

                    b.HasOne("Chiniseapp.Domain.Entities.Entry", null)
                        .WithMany()
                        .HasForeignKey("EntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_score_entries_entries_entry_id");
                });

            modelBuilder.Entity("Chiniseapp.Domain.Entities.Segment", b =>
                {
                    b.HasOne("Chiniseapp.Domain.Entities.Entry", null)
                        .WithMany("Segments")
                        .HasForeignKey("EntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_segments_entries_entry_id");

                    b.HasOne("Chiniseapp.Domain.Entities.Segment", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentSegmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_segments_segments_parent_segment_id");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Chiniseapp.Domain.Entities.Entry", b =>
                {
                    b.Navigation("Segments");
                });

            modelBuilder.Entity("Chiniseapp.Domain.Entities.Segment", b =>
                {
                    b.Navigation("Children");
                });
#pragma warning restore 612, 618
        }
    }
}
